[package]
name = "zellij-remote-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prost = { workspace = true }
bytes = "1.5"

[build-dependencies]
prost-build = "0.11.9"

[dev-dependencies]
proptest = "1.4"
